services:
  # Base de données PostgreSQL
  database:
    image: postgres:15
    container_name: budget-db
    environment:
      POSTGRES_DB: budget
      POSTGRES_USER: budget_user
      POSTGRES_PASSWORD: budget_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - budget-network

  # Backend Quarkus
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: budget-backend
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_PROFILE=prod
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://database:5432/budget
      - QUARKUS_DATASOURCE_USERNAME=budget_user
      - QUARKUS_DATASOURCE_PASSWORD=budget_pass
    depends_on:
      - database
    networks:
      - budget-network

  # Frontend (serveur statique)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: budget-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - budget-network

volumes:
  postgres_data:

networks:
  budget-network:
    driver: bridge